local open, err = package.loadlib(assert(arg[1], "module path is required"), "luaopen_spool")
assert(open, err)
local client = open()
assert(type(client) == "table", "module must return its client API")
assert(type(client._VERSION) == "string", "module must expose its version")
assert(type(client.query) == "function", "query API is missing")
assert(type(client.subscribe) == "function", "subscription API is missing")
assert(type(client.state.get) == "function", "script-state API is missing")
assert(type(client.action.window.balance) == "function", "window action API is missing")
print("Loaded LuaJIT client module " .. client._VERSION .. " without daemon access")
