name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update
    - run: cargo build --release --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: spool-macos
        path: target/release/spool
